import com.intumit.solr.robot.RobotFormalAnswers;
import java.util.List;
import java.lang.StringBuffer;
if(true)
{
    Map<String, List<String>> map = RobotFormalAnswers.getKeyValueMap(ctx.getTenant().getId());
    StringBuffer sb = new StringBuffer();
    int inc = 1;
    sb.append("Map articleMapOne = new HashMap<>();");
    for (Map.Entry<String, String> entry : map.entrySet())
    {
       sb.append("\nList list").append(inc).append(" = Arrays.asList(");
       List stringList = entry.getValue();
       for (int i=0; i < stringList.size(); i++) {
          sb.append("\"").append(stringList.get(i).replace("\"","\\\"")).append("\"");
          if(i > 0 && i < (stringList.size()-1))
              sb.append(",");
       } 
       sb.append(");\n");
       sb.append("articleMapOne.put(\"").append(entry.getKey()).append("\", ").append("list").append(inc++).append(");");
    }
    System.out.println(sb.toString());
}
else
{
    Map articleMapOne = new HashMap<>();
    List list1 = Arrays.asList("補寄電子月結單請點下方 MENU 選擇「客服即時通」由專員為您處理。");
    articleMapOne.put("clickCustomerService", list1);
    List list2 = Arrays.asList("這個問題沒有合適的答案，也許目前我還無法回答您的問題，是否要幫您轉接其他服務管道呢？");
    articleMapOne.put("FORWARD_HEADER_GENERAL", list2);
    List list3 = Arrays.asList("您最近一次帳單結帳後，沒有新增的繳款入帳紀錄");
    articleMapOne.put("noNewPymRecord", list3);
    List list4 = Arrays.asList("好的，請點選“馬上申請”，由客服即時通專員為您服務。");
    articleMapOne.put("applyNowCustomerService", list4);
    List list5 = Arrays.asList("我沒有找到最適合的答案");
    articleMapOne.put("NO_ANSWER_BUT_HAS_RECOMMENDATION", list5);
    List list6 = Arrays.asList("進入留言板");
    articleMapOne.put("FORWARD_OPTION_MESSAGE_BOARD", list6);
    List list7 = Arrays.asList("(已取消)");
    articleMapOne.put("alreadyCancel", list7);
    List list8 = Arrays.asList("目前我還無法回答您的問題，是否要幫您轉接其他服務管道呢？");
    articleMapOne.put("FORWARD_HEADER_NEGATIVE", list8);
    List list9 = Arrays.asList("(獨立額度)");
    articleMapOne.put("singleQuota", list9);
    List list10 = Arrays.asList("小智");
    articleMapOne.put("ROBOT_NAME", list10);
    List list11 = Arrays.asList("帳單還在製作中唷，會在結帳日後 2 個工作天寄出，請您耐心等候唷！");
    articleMapOne.put("waitForTwoDays", list11);
    List list12 = Arrays.asList("帳單結帳日<br/>");
    articleMapOne.put("billCheckoutDate", list12);
    List list13 = Arrays.asList("金額");
    articleMapOne.put("goldAmount", list13);
    List list14 = Arrays.asList("跳針跳針跳針叫我姐姐~~~");
    articleMapOne.put("MANY_REPEAT_SAME_QUESTION", list14);
    List list15 = Arrays.asList("我同意申請電子月結單");
    articleMapOne.put("IAgreeEmail", list15);
    List list16 = Arrays.asList("請選擇選項，或者繼續提問");
    articleMapOne.put("FORWARD_FOOTER_GENERAL", list16);
    List list17 = Arrays.asList("可用額度<br/>");
    articleMapOne.put("availableCredit", list17);
    List list18 = Arrays.asList("您可能還想知道：");
    articleMapOne.put("youMayWannaKnow", list18);
    List list19 = Arrays.asList("」相關問題（請輸入項目編號），看是否有可以幫助您的：");
    articleMapOne.put("SEARCH_TEXT_2_PLAIN", list19);
    List list20 = Arrays.asList("本期帳單交易明細");
    articleMapOne.put("currBillTranDetail", list20);
    List list21 = Arrays.asList("繼續等候客服人員。");
    articleMapOne.put("FORWARD_OPTION_KEEP_WAITING_WEBCHAT", list21);
    List list22 = Arrays.asList("聰明付–本金<br/>聰明付-利息<br/>第QQ期");
    articleMapOne.put("smartPay", list22);
    List list23 = Arrays.asList("關於您詢問的事情，是否由專員直接為您解答？");
    articleMapOne.put("FORWARD_HEADER_MARKETING", list23);
    List list24 = Arrays.asList("參考以下問題，看是否有可以幫助您的：");
    articleMapOne.put("YOU_MAY_WANT_TO_KNOW", list24);
    List list25 = Arrays.asList("很高興還能繼續為您服務");
    articleMapOne.put("CHOOSED_FORWARD_OPTION_STAY_WITH_ROBOT", list25);
    List list26 = Arrays.asList("新北市新店區北新路一段");
    articleMapOne.put("ADDRESS", list26);
    List list27 = Arrays.asList("好的，請點選“馬上申請”，由信貸專員為您服務。");
    articleMapOne.put("applyNowForLoan", list27);
    List list28 = Arrays.asList("請");
    articleMapOne.put("PLEASE", list28);
    List list29 = Arrays.asList("最低應繳金額<br/>");
    articleMapOne.put("miniAmountPayment", list29);
    List list30 = Arrays.asList("繳款截止日<br/>");
    articleMapOne.put("paymentDeadline", list30);
    List list31 = Arrays.asList("網路銀行");
    articleMapOne.put("FORWARD_OPTION_ONLINE_BANKING", list31);
    List list32 = Arrays.asList("目前客服人員都在忙線中，請選擇要繼續等候或者由其他管道為您服務？");
    articleMapOne.put("FORWARD_HEADER_WEBCHAT_BUSY", list32);
    List list33 = Arrays.asList("已使用額度<br/>");
    articleMapOne.put("usedQuata", list33);
    List list34 = Arrays.asList("申請成功後 :<ol><li>七個工作天內簡訊或郵寄本服務約定條款到您在本行留存的行動電話或住家地址。</li><li>您名下所有信用卡/信貸將自動完成電子月 結單申請。</li><li>第一個月如有消費會同時寄送紙本及電子月結單給您，日後僅寄送電子月結單。</li></ol>");
    articleMapOne.put("sevenDays", list34);
    List list35 = Arrays.asList("<br/>自動轉帳");
    articleMapOne.put("autoTransfer", list35);
    List list36 = Arrays.asList("親愛的客戶，網路客服人員服務時間為週一~周日7:30~23:00，目前已超服務時間，您可以選擇：");
    articleMapOne.put("FORWARD_HEADER_WEBCHAT_OFFLINE", list36);
    List list37 = Arrays.asList("」相關問題（請點選或輸入項目編號），看是否有可以幫助您的：");
    articleMapOne.put("SEARCH_TEXT_2_HTML", list37);
    List list38 = Arrays.asList("轉網路電話");
    articleMapOne.put("FORWARD_OPTION_VOICE_CALL", list38);
    List list39 = Arrays.asList("(共用額度)");
    articleMapOne.put("sharingQuota", list39);
    List list40 = Arrays.asList("影像電話");
    articleMapOne.put("FORWARD_OPTION_VIDEO_CALL", list40);
    List list41 = Arrays.asList("按");
    articleMapOne.put("ENTER", list41);
    List list42 = Arrays.asList("請點選連結進入留言板");
    articleMapOne.put("CHOOSED_FORWARD_OPTION_MESSAGE_BOARD", list42);
    List list43 = Arrays.asList("轉真人文字客服");
    articleMapOne.put("FORWARD_OPTION_WEBCHAT", list43);
    List list44 = Arrays.asList("結帳日<br/>");
    articleMapOne.put("checkoutBill", list44);
    List list45 = Arrays.asList("或是可以");
    articleMapOne.put("OR_YOU_CAN", list45);
    List list46 = Arrays.asList("目前溢繳金額<br/>");
    articleMapOne.put("currentOverpayAmout", list46);
    List list47 = Arrays.asList("預計一小時內寄到您的信箱：<br/>");
    articleMapOne.put("emailBox", list47);
    List list48 = Arrays.asList("交易日");
    articleMapOne.put("transDate", list48);
    List list49 = Arrays.asList("無須繳款<br/>");
    articleMapOne.put("noPayment", list49);
    List list50 = Arrays.asList("e起愛地球救救北極熊，註冊電子月結單讓你對帳最簡單。");
    articleMapOne.put("poleBear", list50);
    List list51 = Arrays.asList("這個問題沒有合適的答案，建議您換個不同的問法，或許{{ROBOT_NAME}}就能為您解答哦");
    articleMapOne.put("NO_ANSWER", list51);
    List list52 = Arrays.asList("本期帳單總金額<br/>");
    articleMapOne.put("totalAmountofCurrentBill", list52);
    List list53 = Arrays.asList("請參考螢幕");
    articleMapOne.put("DEFAULT_ROBOT_VOICE_ANSWER", list53);
    List list54 = Arrays.asList("信用總額度<br/>");
    articleMapOne.put("totalCredit", list54);
    List list55 = Arrays.asList("入帳日");
    articleMapOne.put("incomeDate", list55);
    List list56 = Arrays.asList("<a href=\"javascript:;\" class=\"btnTk\" data-id=\"帳單資訊\" data-q=\"帳單應交金額及繳款日\" data-talk=\"查詢我的本期帳單應繳金額及繳款日 。\">帳單資訊</a>");
    articleMapOne.put("BillInfoLink", list56);
    List list57 = Arrays.asList("現在非專員服務時間，請於09:00-21:00再次操作，由客服即時通專員為您服務。");
    articleMapOne.put("notWorkingHourNow", list57);
    List list58 = Arrays.asList("我想繼續跟機器人對話");
    articleMapOne.put("FORWARD_OPTION_STAY_WITH_ROBOT", list58);
    List list59 = Arrays.asList("抱歉~您的問題不是很明確，請更具體描述您的問題，或是參考以下「");
    articleMapOne.put("SEARCH_TEXT_1", list59);
    System.out.println(articleMapOne);
    RobotFormalAnswers.saveMapForInit(ctx.getTenant().getId(),articleMapOne);
}